### ISSUE TITLE
Issue with installer.php on WAMP (.dev setup)

### ISSUE THREAD

**Issue by kbadgley** [statamic/v2-hub#953] opened 2016-09-13 15:10 UTC
### Expected behaviour
Upon clicking "Server looks compatible. Continue to next step" link in installer.php page, should send to .dev/index.php/installer.

### Actual behaviour
Upon clicking "Server looks compatible. Continue to next step" link in installer.php page, should send to index.php/installer.php 

### Steps to reproduce
1.  Be on Windows
2.  Running WAMP
3.  Try to follow expected behavior
4.  Get actual behavior
5   Issue is Line 85 in installer.php file, with the `pathinfo($_SERVER['SCRIPT_NAME'])['dirname']`, this returns a `\`, which breaks the flow and sends to index.php/installer.php

### Server configuration
**Operating system**: Windows

**Web server:** WAMP (Probably all Windows related servers)

**PHP version:** 7.0.4

**Statamic version:** 2.1.9

**Updated from an older Statamic or fresh install:** Fresh install

**List of installed addons:** Default

**Comment by jasonvarga** [comment] 2016-09-16 03:54
Dupe of #888

**Closed by jasonvarga** 2016-09-16 03:54 UTC
Labels: bug
