### ISSUE TITLE
Control Panel not working correctly on HTTPS

### ISSUE THREAD

**Issue by marconucara** [statamic/v2-hub#1306] opened 2017-03-08 14:23 UTC
### Expected behaviour
After the go live i switched all site to https. It should work in front end and cp.

### Actual behaviour
Front end works, cp can't save pages.

### Steps to reproduce
Use https in cp

### Server configuration
**Operating system**:
Amazon linux

**Web server:**
Apache 2.4

**PHP version:**
7.0.14

**Statamic version:**
2.5.4

**Updated from an older Statamic or fresh install:**
from 2.1

### Logs
Console show something like:
```
Mixed Content: The page at 'https://www.pqeyewear.com/cp/collections/entries/news' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.pqeyewear.com/cp/collections/entries/news/get?sort=datestamp&order=desc&page=1'. This request has been blocked; the content must be served over HTTPS.
```

This should be very ease to fix, please let me know.

**Comment by Rias500** [comment] 2017-03-08 16:18
Did you change the APP_URL in the .env file? Make sure this references an https url

**Comment by marconucara** [comment] 2017-03-08 16:58
I did not know existed and can not find anything that mention it in the documentation. Anyway I tried it in development and does not work, doesn't change anything.

**Comment by Rias500** [comment] 2017-03-08 17:01
Ah yes that's because I put that setting in an environment file, check if settings --> system -> locales has https in the url

**Comment by marconucara** [comment] 2017-03-08 17:14
Ok I got it. I just did it too, but nothing changes. And I think it is right that the locales settings does not affect the CP url.

**Comment by marconucara** [comment] 2017-03-09 10:33
Ok i figured it out. $_SERVER['HTTPS'] is not set in some environments, you can read about it [here](http://stackoverflow.com/questions/452375/detecting-https-requests-in-php)  and [here](https://github.com/dmikusa-pivotal/cf-php-apache-buildpack/issues/6).

I tryed to fix the file statamic/core/API/URL.php at line 280, but it wasn't enough so i prefered this htaccess work around:

```
# ------------------------------------------------------------------------------
# $_SEVER['HTTPS'] variable setting
# ------------------------------------------------------------------------------
SetEnv HTTPS on
```

I still can't fix it in valet share / ngrock environment 'cause it doesn't support htaccess, I could change some core file, probably in bootstrap or similiar but I don't need it so much in development env.

Cheers

**Comment by jasonvarga** [comment] 2017-03-16 20:25
In the next release, you can add `use_https: true` to your `system.yaml` file to force https urls.

**Comment by jackmcdade** [comment] 2017-03-16 21:10
Closing this one ahead of the release though because it's a duplicate of #1140 :)

**Closed by jackmcdade** 2017-03-16 21:10 UTC
Labels: pending release
