### ISSUE TITLE
[FR] use of partials in Bard fieldtype

### ISSUE THREAD

**Issue by PeterEmil** [statamic/v2-hub#1770] opened 2018-02-08 11:28 UTC
The way Bard makes writing content and giving clients curated components is its strong USP. To DRY up a fieldset which uses Bard the way is templates work it is very helpful the Bard fieldtype handles the `partial` fieldtype.
```
title: Bard
fields:
  content:
    type: bard
    sets:
      partial_bard:
        fields:
          content:
            type: partial
            fieldset: bard-partial
```

**Comment by jasonvarga** [comment] 2018-02-08 14:05
Dupe of #723 basically.

**Closed by jasonvarga** 2018-02-08 14:05 UTC
