### ISSUE TITLE
Homepage always listed with the default locale title

### ISSUE THREAD

**Issue by peimann** [statamic/v2-hub#2315] opened 2018-12-31 23:17 UTC
**Describe the bug**
Homepage in pages always listed with the default locale title

**To Reproduce**
1. Go to '/pages'
2. Click on 'locales dropdown and select any other locale' (Assume you have added locales more than one)
3. The page will refresh and you'll see the home is still listed by default locale title (assume you have edited homepage and added localized title)

**Expected behavior**
Listing pages in different locales correctly

**Environment details (please complete the following information):**
 - Statamic Version 2.11.3
 - Fresh Install or Upgrade: Fresh
 - OS: macOS Mojave
 - Browser: Chrome/Safari
 - Web Server: Nginx
 - PHP Version: 7.2
 - Addons installed: no

**Comment by jasonvarga** [comment] 2019-02-21 15:28
Duplicate of #2134

**Closed by jasonvarga** 2019-02-21 15:28 UTC
