### ISSUE TITLE
FR: ability to manipulate Redactor minHeight

### ISSUE THREAD

**Issue by mikegraham00** [statamic/v2-hub#1072] opened 2016-10-27 21:26 UTC
### Expected behaviour
Set minHeight in a Redactor setting row. All Redactor fields using that config will respect the height setting

### Actual behaviour
redactor editor min-height is hard-coded into cp.css

**Comment by jasonvarga** [comment] 2016-10-27 21:29
Dupe of #821

**Closed by jasonvarga** 2016-10-27 21:29 UTC
