### ISSUE TITLE
FR: Control/disable middleware for addon routes

### ISSUE THREAD

**Issue by okse** [statamic/v2-hub#771] opened 2016-06-22 12:59 UTC
There is a race condition that cause the session to become corrupt when parallel requests are made to a session-enabled endpoint, see for example laravel/framework#5416 laravel/framework#8172

We have an addon that makes AJAX requests to its own controller via a `/cp/addons/...` route. The problem is that this endpoint has the web middleware, which in turn corrupts the session. We need a way to control middleware for the addon routes explicitly, or at least disable all middleware for given routes to work around the problem.

**Comment by jackwakefield** [comment] 2017-09-30 12:42
I'm running into this too with addon routes, I have 4 requests made on page load, 2 out of 3 times the 4th request fails because the controller thinks the session cookie is no longer valid.

**Comment by jasonvarga** [comment] 2017-09-30 15:03
Can you alleviate this by using Redis for the session? I don't think we'll be touching middleware customization until v3.

**Comment by jackwakefield** [comment] 2017-09-30 16:18
No joy unfortunately. I decided to switch to using JWT for the frontend which is working well.

**Comment by jasonvarga** [comment] 2017-10-10 15:19
Can either one of you provide a reproducible example of this behavior?

**Comment by jackwakefield** [comment] 2017-10-10 19:51
This is a fairly flimsy/extreme example, but if you run `docker-compose up --build` in the output directory,  visit and login to `http://localhost:8080`  (username `jack`, password `jack`) it'll fire 1000 simultaneous requests to a controller which errors when logged out.

Sometimes it doesn't error so you may need to refresh a few times, sometimes it errors once, sometimes it errors for tens/hundreds of requests in a row.

[statamic-race-condition.zip](https://github.com/statamic/v2-hub/files/1373242/statamic-race-condition.zip)

**Comment by jasonvarga** [comment] 2017-10-10 19:52
Okay yeah I was able to get as far as it 'sometimes' happening. It was not consistent. Sounds like the same with your example.

**Comment by jasonvarga** [comment] 2018-06-06 18:31
Closing this issue in favor of #2007

**Closed by jasonvarga** 2018-06-06 18:31 UTC
Labels: feature request
