### ISSUE TITLE
Can't set locale 'en' as secondary

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1038] opened 2016-10-14 16:31 UTC
### Expected behaviour
Working site with 'en' locale as secondary

### Actual behaviour
Site gets through errors.

### Steps to reproduce
1.  Define a primary locale, e.g: tr
2.  Define 'en' as second locale
3.  Refresh website

### Server configuration
**Operating system**: Debian

**Web server:** nginx

**PHP version:** 7

**Statamic version:** 2.1.14

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** none

**Comment by edalzell** [comment] 2016-10-14 18:45
Dupe of #879

**Comment by peimn** [comment] 2016-10-14 21:26
I am so curious about localization, please excuse me.

**Closed** 2016-10-24 18:08 UTC

**Comment by jasonvarga** [comment] 2016-10-24 18:09
Is this the same issue as #879?

Anyway, you said the behavior is "site gets errors". We need to know the errors to help you.

**Comment by peimn** [comment] 2016-11-17 06:53
It causes 404 errors on assets, it tries to make path for assets from en locale.
