### ISSUE TITLE
Trim on Save Form

### ISSUE THREAD

**Issue by shabbarabbas** [statamic/v2-hub#2168] opened 2018-09-11 12:24 UTC
i am in situation where email verification fail if there is a space after it , and it is hard to judge the space with eye , is there any solution for this ??
![blank space](https://user-images.githubusercontent.com/6230508/45359924-7af8d200-b5e7-11e8-91ac-f62906b5268a.png)

**Comment by jackmcdade** [comment] 2018-09-14 14:34
Duplicate of #2133

**Closed by jackmcdade** 2018-09-14 14:34 UTC
Labels: feature request
