### ISSUE TITLE
Add user; doesn't show up list until I clear cache

### ISSUE THREAD

**Issue by pmeissner** [statamic/v2-hub#969] opened 2016-09-19 12:35 UTC
### Expected behaviour
When I add a user within CP and save, the `cp/users` list of users should show the new user.

### Actual behaviour
The `cp/users` list is missing the new user.

### Steps to reproduce
1.  Add user
2.  Save user

### Server configuration
**Operating system**: Linux

**Web server:** Apache 

**PHP version:** 7.0.11

**Statamic version:** 2.1.10

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** CacheManager

### Logs
I got nothin'

After I manually clear the cache using CacheManager, the new users show up in the `cp/users` list.

**Comment by jasonvarga** [comment] 2016-09-19 13:13
Dupe of #947 and fixed for next release.

**Closed by jasonvarga** 2016-09-19 13:13 UTC
