### ISSUE TITLE
Markdown not rendering image asset with spaces

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#673] opened 2016-05-10 19:22 UTC
### Steps to reproduce
1. Upload image asset with spaces (image name.png) in markdown content field

### Expected behaviour

Markdown should output correct image markup.

### Actual behaviour

Markdown outputs:

```
<p>![alt tag](assets/image/blog/file name.png)</p>
```

**Comment by jasonvarga** [comment] 2016-05-17 16:12
It looks like this is intended behavior.

```
![](/path/with/spaces in filename.jpg)
Outputs: ![](/path/with/spaces in filename.jpg)

![]("/path/with/spaces in filename.jpg")
Outputs: <img src="/path/with/spaces in filename" alt="" />
But doesn't load the image.

![](/path/with/spaces%20in%20filename.jpg)
Outputs: <img src="/path/with/spaces%20in%20filename.jpg" alt="" />
```

So, we should be managing the spaces for you, whether that means encoding them when inserting in a markdown field, or removing spaces when you create the asset.

Either way, it's a different issue so I'm closing this. Thanks!

**Closed by jasonvarga** 2016-05-17 16:12 UTC
