### ISSUE TITLE
FR: create a new entry of a relationship while authoring the parent entry

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#748] opened 2016-06-09 22:45 UTC
If I'm creating a new blog article as an example and I want to assign an author (from a collection) but the author doesn't yet exist, I'd like to create that on the fly without having to leave the blog post.

**Comment by jasonvarga** [comment] 2016-06-10 01:16
Pretty much a dupe of https://github.com/statamic/v2-hub/issues/283

**Closed by jasonvarga** 2016-06-10 01:16 UTC
