### ISSUE TITLE
Algolia Major update: PHP API Client

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1496] opened 2017-07-07 18:24 UTC
When I logged into Algolia today I saw this warning. 

![screenshot 2017-07-07 14 20 00](https://user-images.githubusercontent.com/414211/27971155-8eccc942-631f-11e7-88d0-f9196ae2d8cc.png)

**Critical update Php API client 1.10.2 > 1.18.0** 
Over the past 24 hours you have been using an outdated version of our API client, please upgrade to the latest version

Details:
> Major update: Php API client
> The following major versions have been released since 05 Aug 2016. We highly recommend to update your API client to the latest version to fix any potential bug:
> 1.12.1IMPROVED RETRY STRATEGY
> The retry strategy switching to our second DNS provider has been improved to avoid timeouting again and again if our first DNS provider is experiencing an outage or DDOS.
> 
> The outdated check is done once per day so you might see that message for the next 24 hours.
> The Algolia API will continue to work with you current version, even if not recommended.

**Comment by jasonvarga** [comment] 2017-07-07 18:25
What Statamic version are you on?

**Comment by mikemartin** [comment] 2017-07-07 19:02
@jasonvarga Ah, never thought of that.. this site is 2.1.19. Haven't gotten around to the 2.2 assets update on this one.

**Comment by jasonvarga** [comment] 2017-07-07 19:04
We updated the Algolia client in 2.5.11

Dupe of #1438 

🎩

**Closed by jasonvarga** 2017-07-07 19:04 UTC
