### ISSUE TITLE
CP: new Collection without setting Fieldset

### ISSUE THREAD

**Issue by JayVerb** [statamic/v2-hub#443] opened 2016-02-16 02:57 UTC
I know, I know. It's stupid and I was in a hurry. Always trying to think through processes.

Creating a new collection without selecting a fieldset results is spinning progress when adding new collection content. I think it should be blank on initial creation, but if nothing is set on Save, maybe set it to Default. Not sure the best way to handled as the default may be deleted. Maybe require setting on Collection creation or display "No Fieldset Selected" on the creating new collection content.

**Comment by jasonvarga** [comment] 2017-03-17 14:44
Not sure what the issue is here. Closing because it's pretty old and seems fine now.

You don't need to set a fieldset on a collection. It'll fall back to the default in `theming.yaml`

**Closed by jasonvarga** 2017-03-17 14:44 UTC
