### ISSUE TITLE
Submission->id() doesn't set the id if it doesn't exist

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#984] opened 2016-09-24 01:33 UTC
in Submission `id()`

 ```
    public function id($id = null)
    {
        if (is_null($id)) {
            return $this->id ?: time();
        }

        $this->id = $id;
    }
```

if there is no id it passes back the `time()` but doesn’t actually *set* the id for the submission

That means calls to `->id()` returns different results when using a debugger.

**Comment by edalzell** [comment] 2016-09-24 01:37
for those that care, this is the work around:
```
            $submission_id = $submission->id();
            $submission->id($submission_id);
```

**Comment by jasonvarga** [comment] 2016-09-24 15:18
Looking back at this, it is kinda stupid. However it worked because everything was done at once.

In `$form->submissions()`, we set `$submission->id()` to the filename, which would be the timestamp. Check out `Form.php` lines 48-64.

The problem which you pointed out somewhere else is when there's multiple submissions in the same second.

I'm gonna close this issue. Your other one (#982) is enough

**Closed by jasonvarga** 2016-09-24 15:18 UTC

**Comment by edalzell** [comment] 2016-09-24 15:25
This is different problem though. In my code I was using the `creating` event, and grabbing the submission id for something. Then when using the debugger and the submission was saved by Form, the `id` was different because it was in a different second (because debugger time).

Work around was to grab the time once and set the submission id myself, which feels goopy. Or use the `created` event I guess.

Fixing the other problem won't fix this one, unless I misunderstand.

Anyway, I do have workarounds.

**Comment by jasonvarga** [comment] 2016-09-24 15:27
The `id` method will set the id if you pass it one, and get the id if you don't. It's not supposed to set it if you're just getting it.

It works as intended.

If we work out a better way to assign IDs, which is what needs to happen in the other issue, this issue will disappear.

**Comment by edalzell** [comment] 2016-09-24 15:30
ok, but multiple calls to it can return different ids, which seems wrong.

But I understand you're trying to solve the bigger issue.

**Comment by jasonvarga** [comment] 2016-09-24 15:30
Doing what you did was the way to go about it.

**Comment by edalzell** [comment] 2018-09-06 02:48
Now that submission id's are microtime, this issue is back.

**Comment by jasonvarga** [comment] 2018-09-06 03:37
What's different?

**Comment by edalzell** [comment] 2018-09-06 04:06
you closed this because you thought it was based on the referenced issue. But I still have this issue. Call `$submission->id()` more than once in a `Form.submission.creating` listener and you get two diff values.

**Comment by JesseLeite** [comment] 2018-09-07 00:59
@edalzell I can't reproduce your issue.  This is what I'm doing:

```php
class FormCreatingListener extends Listener
{
    public $events = [
         'Form.submission.creating' => 'logId',
    ];

    public function logId($submission)
    {
        \Log::info($submission->id());
        sleep(2);
        \Log::info($submission->id());
    }
}
```
Which logs:
```
[2018-09-07 00:55:38] dev.INFO: 1536281738.9911
[2018-09-07 00:55:40] dev.INFO: 1536281738.9911
```
What are you doing differently to see two different values?

**Comment by edalzell** [comment] 2018-09-07 02:50
If you leave the second one out (like I'm doing) and let Statamic set it back up the calling chain, do you get a submission with an `id` that matches the log?

**Comment by JesseLeite** [comment] 2018-09-07 14:18
![screen shot on 2018-09-07 at 10_15_04](https://user-images.githubusercontent.com/5187394/45224092-1f48e480-b287-11e8-8538-bd05e469134a.png)

And if I sleep _before_ getting the ID in my listener, they still match, just to prove it's same instance even with delayed microtime, if that makes sense.

**Comment by edalzell** [comment] 2018-09-07 14:43
OH I'M AN IDIOT. I'm on version 2.9.8. Sheesh. SORRY.

**Comment by JesseLeite** [comment] 2018-09-08 00:40
Haha, all fixed on current version then? 👍
