### ISSUE TITLE
Glide tag with fm="pjpg" (progressive JPG) uses extension .pjpg not .jpg

### ISSUE THREAD

**Issue by gmcz** [statamic/v2-hub#1409] opened 2017-05-08 15:34 UTC
### Expected behaviour
I expect that a .jpg file would be created

### Actual behaviour
A file with the extension ".pjpg" is created

### Steps to reproduce
1.  Use a glide tag with `fm="pjpg"`
2.  Check the output

### Server Details

**Operating System**: Mac & Linux

**Web Server:** Nginx

**PHP Version:** 7

**Statamic Version:** 2.5.9

**Comment by jackmcdade** [comment] 2017-05-08 19:03
Looks like that was fixed in Glide 1.2 (we're on 1.1.x). Will get that sorted out. 👍

**Comment by jackmcdade** [comment] 2017-05-08 19:14
Actually just kidding, we _are_ running the latest version of Glide, and I don't see an issue with `fm="pjpg"`. How do I recreate your issue exactly?

**Comment by jasonvarga** [comment] 2017-05-09 15:33
Confirmed bug (in Glide) - but I'll fix it and open a PR.

**Comment by jasonvarga** [comment] 2017-05-09 21:09
Fixed for next release.

**Comment by gmcz** [comment] 2017-05-10 19:07
Thanks, Gentlemen! 👍

**Closed** 2017-05-16 17:50 UTC
Labels: bug, pending release
