### ISSUE TITLE
FR: Descriptive Replicator set titles

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1045] opened 2016-10-17 18:54 UTC
When Replicators and Grids are collapsed, it can be difficult to identify which is which. 

<img width="753" alt="screenshot 2016-10-17 11 49 44" src="https://cloud.githubusercontent.com/assets/414211/19450819/d17d5a34-945f-11e6-8efa-04b81b64dea7.png">

Could you treat the Replicator list group titles the same way as the saved Page title? 
For instance, if a Replicator set has a Title field, could you display that as the list group title?

<img width="751" alt="screenshot 2016-10-17 11 47 23" src="https://cloud.githubusercontent.com/assets/414211/19450866/f8543664-945f-11e6-82f8-2b787cb8ba39.png">

**Comment by jasonvarga** [comment] 2016-10-17 18:54
Good FR, but its a dupe of #260

**Closed by jasonvarga** 2016-10-17 18:54 UTC
