### ISSUE TITLE
Bad link on Statatmic System Settings

### ISSUE THREAD

**Issue by ogieogalthorpe** [statamic/v2-hub#2041] opened 2018-06-28 16:37 UTC
**Describe the bug**
The link to the License settings in the Statamic account on the System Settings page (/cp/settings/system) is bad. Instead of linking out to the Statamic, site, it is appending the Statamic URL to the path of the current site. (e.g. https://site-domain.com/account.statamic.com/licenses when it should be https://account.statamic.com/license)

**To Reproduce**
1. Sign in to Control Panel (/cp)
2. Click on Settings in the left menu
3. Click on the "Statamic Account" link beside Licenses
4. You receive a "Page Not Found" error

**Expected behavior**
The link should take you to the Statamic site's Account page

**Environment details (please complete the following information):**
 - Statamic Version 2.8.12

**Comment by edalzell** [comment] 2018-06-28 16:57
I can't reproduce this on 2.9.8

**Comment by jasonvarga** [comment] 2018-06-28 16:59
This was fixed in 2.9.7

**Closed by jasonvarga** 2018-06-28 16:59 UTC
