### ISSUE TITLE
Actions menu for the last item in the assets page is not visible entirley

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#1681] opened 2017-12-15 22:37 UTC
In Chrome and Firefox (not tested on others):
<img width="1048" alt="screen shot 2017-12-16 at 2 02 32 am" src="https://user-images.githubusercontent.com/5695187/34063194-cac873d2-e205-11e7-9549-96f6d7f280b9.png">

**Comment by jasonvarga** [comment] 2017-12-15 22:38
Dupe of #1502 and #1630

**Closed by jasonvarga** 2017-12-15 22:38 UTC
