### ISSUE TITLE
Bug: If using a section fieldtype immediately after Title, margin padding goes away. 

### ISSUE THREAD

**Issue by tkoosis** [statamic/v2-hub#1868] opened 2018-04-04 23:16 UTC
### Expected behaviour
Section should have margin bottom spacing as usual. 

### Actual behaviour
Instead of 32px bottom margin, last-child css is applied and removes it. 
```
.publish-fields>.form-group:last-child {
    margin-bottom: 0;
}
```

### Steps to reproduce
1.  Make a fieldset
2.  Add a `section` fieldtype and arrange it right under the Title
3.  save and add a new instance of that fieldset

You should see the input box bleeding over into the section:
<img width="860" alt="screenshot 2018-04-04 15 15 13" src="https://user-images.githubusercontent.com/170316/38339498-5fe4b8ae-3823-11e8-8e63-1c19760cbbb5.png">

### Server Details

**Operating System**:
n/a

**Web Server:**
n/a
**PHP Version:**
n/a
**Statamic Version:** 2.8.10

**Updated from an older Statamic or fresh install:**
Fresh

**List of installed addons:**
none

### Logs
If any logs (browser, server, or Statamic) are appropriate...
n/a

**Comment by jasonvarga** [comment] 2018-04-17 14:06
Dupe of #1865

**Closed by jasonvarga** 2018-04-17 14:06 UTC
