### ISSUE TITLE
FR: display character count for a field

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#978] opened 2016-09-22 18:41 UTC
I feel like https://github.com/LkeMitchll/statamic-limited should be a core feature if you have validation set for max length on a field

**Comment by jackmcdade** [comment] 2016-09-22 19:13
Hi Steven! This is a duplicate of #822, which happens to be yours as well. 😂

**Closed by jackmcdade** 2016-09-22 19:13 UTC

**Comment by jasonvarga** [comment] 2016-09-22 19:15
He's trying to game the system. I'm onto you, @stevieg83

**Comment by jackmcdade** [comment] 2016-09-22 19:15
![No soup!](https://cdn.meme.am/instances/65152924.jpg)
