### ISSUE TITLE
Can't sort users by name

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1609] opened 2017-10-02 05:53 UTC
### Expected behaviour
The users should be ordered by name when clicking on the name column head in the users list.

### Actual behaviour
Nothing happens, neither up or down...

### Steps to reproduce
1.  Login to CP
2.  Go to the users page
3.  Click the column head for name

(the columns for username and email works)

### Server Details

**Web Server:**
MAMP / Nginx

**PHP Version:**
7.0.20

**Statamic Version:**
2.6.9

### Logs
No errors

**Comment by edalzell** [comment] 2017-10-02 15:45
Dupe of #1410?

**Closed** 2018-03-29 16:19 UTC
