### ISSUE TITLE
custom rules for cp roles

### ISSUE THREAD

**Issue by 4kets** [statamic/v2-hub#1760] opened 2018-01-29 15:41 UTC
I was just wondering if there a way to have custom rules like "editor role can make new pages but not publish them" for roles without super user.

**Comment by jasonvarga** [comment] 2018-02-05 15:03
There is currently no way to add custom permissions.

Dupe of #451

**Closed by jasonvarga** 2018-02-05 15:03 UTC

**Comment by simonhamp** [comment] 2018-02-19 15:16
@4kets I'm after something similar, but then I realised our use-case will be to publish on a staging server and only deploy to live once everything is ironed out. If you can achieve something similar, I think those are [favoured approaches](https://docs.statamic.com/knowledge-base/version-control) at the moment.
