### ISSUE TITLE
Form editor field not updating.

### ISSUE THREAD

**Issue by jaesung2061** [statamic/v2-hub#1094] opened 2016-11-08 15:19 UTC
### Expected behaviour
Expect `column` field in form editor to update.

### Actual behaviour
Does not update `column` field, but returns successful response. All other fields update as expected.

### Steps to reproduce
1.  Create or edit form in control panel.
2.  Make any change to `column` field.
3.  Save.

### Server configuration
**Operating system**: Mac OS X

**Web server:** Nginx 1.10.1

**PHP version:** 7.0.11

**Statamic version:** 2.1.17

**Updated from an older Statamic or fresh install:** No

**List of installed addons:** None

**Comment by dannyuk1982** [comment] 2016-11-08 15:20
I get this too

**Comment by jackmcdade** [comment] 2016-11-15 02:29
Dupe of #789 and #593.

**Closed by jackmcdade** 2016-11-15 02:29 UTC
Labels: bug, pending release
