### ISSUE TITLE
Site will not load when queue:listen is running

### ISSUE THREAD

**Issue by rdarcy1** [statamic/v2-hub#2159] opened 2018-09-03 14:42 UTC
**Describe the bug**
When running a background CLI process such as `queue:listen`, the Stache lock prevents any other processes from completing, including serving the site.

**To Reproduce**
1. Start a queue worker
2. Try to load the site
3. Lock will prevent the second process from completing

**Fix**
I think a possible fix is to release the lock immediately after starting the `queue:listen` command, since the child `queue:work` commands should deal with their own locking.

The following seemed to work locally with `queue:listen` running, but not in production with Forge workers, hence the workaround below.

```php
// ListenCommand.php

namespace Statamic\Addons\Overrides\Commands;

class QueueListen extends \Illuminate\Queue\Console\ListenCommand
{
    public function fire()
    {
        app('stache')->lock()->release();
        parent::fire();
    }
}
```

```php
// Override command container binding in service provider

$this->app->extend('command.queue.listen', function ($command, $app) {
    $listener = $app->make('queue.listener');

    return new QueueListen($listener);
});
```

**Workaround**
Currently I've disabled the lock by registering a dummy array lock store:

```php
$this->app->extend(Stache::class, function (Stache $stache, $app) {
    $store = new ArrayLockStore;
    $name = config('cache.prefix') . ':stache-lock';

    $lock = new Lock(new Key($name), $store);

    return $stache->lock($lock);
});
```

Not a good solution, but at the moment having a queue is more important than the lock.

**Environment details (please complete the following information):**
 - Statamic Version 2.10.4
 - Fresh Install or Upgrade: Upgrade
 - PHP Version: 7.1

**Comment by jasonvarga** [comment] 2018-09-04 15:10
Is this the same as #2099 ?

**Comment by rdarcy1** [comment] 2018-09-04 15:12
Yes looks like the same issue. Apologies, didn't see that when searching.

**Comment by jasonvarga** [comment] 2018-09-04 15:13
Funnily enough, we've added a `NullLockStore` to disable the lock for a different reason, which will be in the next release. You'll be able to to add `stache_lock_enabled: false` to your `caching.yaml` to disable the lock.

No worries about the dupe. You made it a little more obvious to me what the issue is.

**Comment by jasonvarga** [comment] 2018-10-31 17:34
Does this still happen in 2.10.7?

**Comment by jasonvarga** [comment] 2018-10-31 17:39
I reverted a change in 2.10.6 that I suspected fixed this issue, and the site locked up. So, I believe 2.10.6 fixes this. Let me know if you're still running into it.

**Closed by jasonvarga** 2018-10-31 17:39 UTC
Labels: bug

**Comment by rdarcy1** [comment] 2018-11-16 15:30
I've just updated from 2.10.4 to 2.11.2 and all seems to be running fine now without my workaround. Thanks!
