### ISSUE TITLE
Logging is using wrong timezone

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#927] opened 2016-09-06 03:01 UTC
### Steps to reproduce
1. Write to the log
2. Open log and look at the timestamp

### Expected behaviour
Logging should be timestamped to PHP timezone time

### Actual behaviour
Uses `default_timezone` instead of `date.timezone`

![phpinfo 2016-09-05 11-30-00](https://cloud.githubusercontent.com/assets/6069653/18260506/4fa2db56-73a3-11e6-9002-06ac72ba3d28.png)

Re the below code:
```
[2016-09-06 02:54:05] dev.WARNING: foo  
[2016-09-05 19:55:44] dev.WARNING: foo  
```

the first one is a standard logging call. The second is after calling: 

```
        date_default_timezone_set(ini_get('date.timezone'));
        \Log::warning('foo');
```

**Comment by jasonvarga** [comment] 2016-09-06 03:02
Dupe of #458

**Closed by jasonvarga** 2016-09-06 03:02 UTC
