### ISSUE TITLE
Taxonomies don't seem to invalidate static cache

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1753] opened 2018-01-25 15:27 UTC
### Expected behaviour
Using the following invalidation rules, I expect the homepage to be cleared after editing a Term:

```yaml
stache_always_update: false
static_caching_enabled: true
static_caching_type: file
static_caching_file_path: static
static_caching_ignore_query_strings: false
static_caching_lock_hold_length: 0
static_caching_exclude:
  - /sitemap*
static_caching_invalidation:
  pages:
    /solutions:
      urls:
        - /
  collections:
    careers:
      urls:
        - /
        - /careers
    partners:
      urls:
        - /
  taxonomies:
    categories:
      urls:
        - /
    locations:
      urls:
        - /
        - /careers*
```

### Actual behaviour
Nada. When editing a Category or Location the static cache remains the same.

FYI: the Pages and Collections invalidation rules **do work** as expected.

### Server Details
**Statamic Version:**
2.8.3

**Comment by jackmcdade** [comment] 2018-10-26 21:12
While technically #1843 is a duplicate of this issue, that one has more detail. So...

Closing this sucker down.

**Closed by jackmcdade** 2018-10-26 21:12 UTC
