### ISSUE TITLE
Navigation broken on /subfolder Installation

### ISSUE THREAD

**Issue by RastaTux** [statamic/v2-hub#1279] opened 2017-02-28 19:48 UTC
### Expected behaviour
The example Redwood page should have a navigation and you should be able to edit existing pages in the control panel.

### Actual behaviour
No Navigation is shown and the Control panel page section looks like no page was added- Even when the standard ones are visible in the statamic folder and when i add a new page, it will be added as 8th page (Still not shown in cp, anyways).

### Steps to reproduce
1.  Take the 2.5.3 statamic 2 package and shove it into a subfolder of your localhost/ subfolder of server
2.  Change the .htaccess, index sideroot and sytem.yaml locales to the subfolder f.e. /test/
3.  Go to website and wonder, where navigation items got lost.
4. Go to control panel and wonder, why the pages are not shown there.

### Server configuration
**Operating system**: Linux Ubuntu

**Web server:** Apache

**PHP version:** 5.6, 7.0, ...

**Statamic version:** 2.5.3

**Updated from an older Statamic or fresh install:** no

**List of installed addons:** none

**Comment by jackmcdade** [comment] 2017-03-16 20:54
Working on fixing this up.

**Comment by jackmcdade** [comment] 2017-03-16 21:09
Closing this one though because it's a duplicate of #1276 (same issue).

**Closed by jackmcdade** 2017-03-16 21:09 UTC
Labels: bug
