### ISSUE TITLE
form:set scope issue with form:success

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#661] opened 2016-05-03 07:53 UTC
### Steps to reproduce
1. Create multiple forms with formsets
2. Create multiple success messages
3. Submit either form on the front end with the correct fields filled in
### Expected behaviour

When you submit a form only the success message for the submitted form should display not both success messages using the following example:

```
{{ form:set is="contact" }}
  {{ if {form:success} }}
        Thank you for your message, one of the team will be in touch shortly.
  {{ /if }}
{{ /form:set }}

{{ form:set is="download" }}
  {{ if {form:success} }}
        Thank you for joining our mailing list.
  {{ /if }}
{{ /form:set }}
```
### Actual behaviour

Both messages display on successful submission of one of the forms. A quick note, this behaviour works as expected for the error message so using the above example works fine when an error is encountered with one of the fields:

```
{{ form:set is="contact" }}
  {{ if {form:errors} }}
        Contact error!
  {{ /if }}
{{ /form:set }}

{{ form:set is="download" }}
  {{ if {form:errors} }}
        Download error!
  {{ /if }}
{{ /form:set }}
```

**Comment by jcohlmeyer** [comment] 2016-08-23 16:34
Just in case anybody else is having this issue @jackmcdade suggested that you could redirect to another page on success as a work around or possibly a better UX choice. Docs for that are here: https://docs.statamic.com/reference/tags/form-create

**Comment by edalzell** [comment] 2017-02-14 23:44
@jasonvarga I suggest this be closed as it is a dupe of #1190.

**Closed** 2017-03-17 15:40 UTC
Labels: bug
