### ISSUE TITLE
Fieldset other than default.yaml not being saved for a page

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#2069] opened 2018-07-18 09:24 UTC
**To Reproduce**
1. Create a new page, choose a fieldset other than default
2. Enter data and save it
3. Open it again, it is using the default fieldset

The yaml for that page lists 
```
fieldset: null
```

**Environment details (please complete the following information):**
 - Statamic Version 2.10.0

**Comment by dannyuk1982** [comment] 2018-07-18 09:34
I am getting this in 2.9.8 too

**Comment by jasonvarga** [comment] 2018-07-18 13:47
Duplicate of #2068, essentially.

**Comment by dannyuk1982** [comment] 2018-07-18 14:16
Ah yes, I hadn't thought they would be related

**Closed** 2018-07-18 21:00 UTC
Labels: pending release
