### ISSUE TITLE
'Do you want to leave this site?' message appears when no edits have been made, when using certain fieldtypes

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1559] opened 2017-08-18 06:42 UTC
In the CP there is a warning that pops up if you try to exit a page when you have edited something but haven't saved. 

```
**Do you want to leave this site?**
Changes that you made may not be saved.
```

This is a great feature and has saved my bacon on several occasions - however there is an annoying facet to this function in that is seems to occur if you scroll on a page or focus on a field even if you haven't made an edit. 

Personally I think only an edit on the page should cause the warning to occur, NOT scrolling or focusing on a field, otherwise it is really annoying.

I have had clients tell me this annoys them a lot, and it has annoyed me quite a bit whilst developing.

**Comment by rrelmy** [comment] 2017-08-18 12:55
Could be related to #1480

I also just realized that the warning is triggered when focusing my [charfield](https://github.com/subpixel-ch/statamic-charfield) ([issue](https://github.com/subpixel-ch/statamic-charfield/issues/1))

**Comment by jasonvarga** [comment] 2017-08-18 12:59
We only enable the popup when something _does_ change. So, something might unintentionally be getting changed. Perhaps when a field is loaded. Can you show me a fieldset where this is happening?

**Comment by FR6** [comment] 2017-08-18 14:01
@jasonvarga You are right, it works properly with the demo fieldsets.

I find out that it triggers the alert when there is specifically an Assets field and there is a scroll in the page:

![image](https://user-images.githubusercontent.com/286685/29462071-0cd88f36-83fc-11e7-985b-4cf6fc84f184.png)

**Comment by rrelmy** [comment] 2017-08-20 10:38
I can not reproduce the scrolling issue but I did reproduce a general problem that maybe related to this issue.

If you focus an empty text field the `data` property of the component changes from `null` to empty string which triggers the `changesMade` event.

### Steps to reproduce
1.  Open a fieldset with an empty Create Title
2.  Focus the field
3.  Navigate away and see the alert

**Comment by edalzell** [comment] 2017-08-22 20:32
I see this on an addon settings page when I have custom suggest modes

**Comment by jasonvarga** [comment] 2017-08-22 20:33
I've fixed this in a branch. Haven't labeled this issue as pending release because I don't know if it will be the next one or not.

However, it's fixed. Will be released eventually.

**Comment by anthubbard** [comment] 2017-08-22 21:45
\o/

&#128131;

Jason Varga, you are amazing

**Closed** 2017-08-28 19:39 UTC
Labels: pending release
