### ISSUE TITLE
Missing translation / locale

### ISSUE THREAD

**Issue by danieljwestman** [statamic/v2-hub#1647] opened 2017-11-08 09:22 UTC
### Expected behaviour
Everything in CP should be able to be translated in my locale

### Actual behaviour
The new "Show/hide drafts" in pages list isn't.

### Server Details

**Web Server:**
Mamp

**PHP Version:**
7

**Statamic Version:**
2.7.2

<img width="402" alt="skarmavbild 2017-11-08 kl 09 18 03" src="https://user-images.githubusercontent.com/20950568/32541024-55407e64-c466-11e7-8b4a-09c3a7386288.png">

**Comment by ebeauchamps** [comment] 2017-11-08 17:27
Duplicate of #1629

**Closed** 2018-01-10 20:24 UTC
Labels: pending release
