### ISSUE TITLE
Workshop: no way to return errors from Listener

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1142] opened 2016-12-04 04:50 UTC
### Expected behaviour
Be able to return errors in my `content.saved` Listener.

### Actual behaviour
Can't return errors

**Comment by edalzell** [comment] 2017-04-08 19:13
cc @jasonvarga and this was the other.

**Comment by jasonvarga** [comment] 2018-06-06 14:36
Dupe of #1109

**Closed by jasonvarga** 2018-06-06 14:36 UTC

**Comment by edalzell** [comment] 2018-08-20 22:21
How do I return errors from a Workshop event?
