### ISSUE TITLE
FR: Copy/Duplicate an entry of page

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1062] opened 2016-10-25 14:02 UTC
The ability to copy/duplicate an existing page or entry in a collection - useful for sites that have lots of similar pages or entries (i.e. events) where a lot of time would be saved being able to duplicate another page and work from there.

I am guessing this is fairly simple to achieve, with just the slug/title/ID needing to be altered for the copy.

Several clients have asked me about this one, and one decided they didn't want to go with Statamic purely on this (much of their daily site content management involved setting up events which were very similar to others).

**Comment by jasonvarga** [comment] 2016-10-25 14:03
Dupe of #681

**Comment by dannyuk1982** [comment] 2016-10-25 14:04
Shut down in < 5 seconds, you are on fire today Jason!

**Closed by jasonvarga** 2016-10-25 14:03 UTC

**Comment by jasonvarga** [comment] 2016-10-25 15:32
🔥 🔥 🔥
