### ISSUE TITLE
FR: Select parent page when creating a new child page in CP

### ISSUE THREAD

**Issue by anthubbard** [statamic/v2-hub#1555] opened 2017-08-16 02:21 UTC
I know you can create a child page when clicking the 3 little dots to the right of a page in the CP, but I much preferred (and so do at least 2 of my clients) the ability to choose the parent page when pressing 'create page' from the main button in the CP.

**Comment by jasonvarga** [comment] 2017-08-18 15:27
Dupe of #68

**Closed by jasonvarga** 2017-08-18 15:27 UTC
