### ISSUE TITLE
FR: Add a hash to open sneak peak

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1083] opened 2016-11-03 12:36 UTC
### Expected behaviour
Would be great if you navigated to:
`http://www.mysite.com/cp/pages/edit/page-name#sneak-peak`
that opened up sneak peak if you are logged in

Then that will allow buttons to be added to every page on the frontend to open that page straight up in sneak peak - great for very un-tech-savvy clients

**Comment by jasonvarga** [comment] 2016-11-03 13:04
Dupe of #883

**Closed by jasonvarga** 2016-11-03 13:04 UTC
