### ISSUE TITLE
FR: Add a Deleting event

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#1441] opened 2017-06-01 03:20 UTC
Right now you send a `Deleted` event whenever content is deleted. This however, does not allow an addon do to anything w/ the deleted data because it's gone by the time that event is sent.

If there was a `Deleting` event as well that had the actual data object, then addons could do something, like a soft delete, with the data.

Code would look something like (in Content.php in `delete`:
```
                // Whoever wants to know about it can do so now.
                $event_class = 'Statamic\Events\Data\\' . ucfirst($this->contentType()) . 'Deleting';
                event(new $event_class($this->id(), $paths->all()), $this);
                File::disk('content')->delete($path);
```

**Comment by jackmcdade** [comment] 2018-06-06 17:16
Dupe of the super thorough #687.

**Closed by jackmcdade** 2018-06-06 17:16 UTC
Labels: feature request
