### ISSUE TITLE
Image edit button not works after selecting image when creating new collection entry

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#746] opened 2016-06-09 16:41 UTC
When I click that pencil it doesn't do any thing.
There is not any error in console.

<img width="381" alt="screen shot 2016-06-09 at 9 09 31 pm" src="https://cloud.githubusercontent.com/assets/5695187/15938008/7def099c-2e86-11e6-9322-c3667531354f.png">

**Statamic version:** 2.0.7

**Comment by jasonvarga** [comment] 2016-06-09 17:38
Duplicate of https://github.com/statamic/v2-hub/issues/513

**Closed by jasonvarga** 2016-06-09 17:38 UTC
