### ISSUE TITLE
Linebreaks in markdown front-matter fields don't work

### ISSUE THREAD

**Issue by timmschroeder** [statamic/v2-hub#1324] opened 2017-03-15 09:58 UTC
### Expected behaviour
In a custom markdown field there should be a linebreak <br /> when I type two spaces at the of the line.

### Actual behaviour
No linebreaks. If I save the page the two spaces are gone.

**Comment by jasonvarga** [comment] 2017-03-15 12:49
Dupe of https://lodge.statamic.com/questions/2242-how-to-do-a-linebreak-in-v2-with-markdow but I don't see any issue here so I'll leave it.

It's the YAML parser we're using, which strips whitespace. Just haven't found a fix yet.

**Comment by jcohlmeyer** [comment] 2017-04-27 18:57
There is now an option to use `hard_warp` in php markdown. It could be a parameter on `markdown`?

https://github.com/michelf/php-markdown/commit/a0012c0590dc23007e8fafcb441852286e448352

**Comment by jasonvarga** [comment] 2017-08-28 17:56
In 2.6.7, there is an option to enable @jcohlmeyer 's hard wrap behavior. This could be a solution for you until the bug in the YAML parser is fixed.

**Closed** 2018-05-21 17:47 UTC
Labels: blocked, pending 2.9
