### ISSUE TITLE
FR: Pass through Content data to Deleted event

### ISSUE THREAD

**Issue by aryehraber** [statamic/v2-hub#1902] opened 2018-04-27 11:06 UTC
It would be great if Content data could be passed in with the `Deleted` event to allow actions using that data before it is gone.

Currently hacked the following into Core, but would be great to see something like this supported natively.

Another options would be a `Deleting` event before the Content is gone, as requested in issue https://github.com/statamic/v2-hub/issues/1441

In `statamic/core/Data/Content/Content.php`:

```php
public function delete()
{
    $data = $this->data();

    // ...

    $event_class = 'Statamic\Events\Data\\' . ucfirst($this->contentType()) . 'Deleted';
    event(new $event_class($this->id(), $paths->all(), $data));
}
```

In `statamic/core/Events/Data/DataDeleted.php`

```php
abstract class DataDeleted extends Event
{
    public function __construct($id, array $paths, $data = null)
    {
        $this->id = $id;
        $this->paths = $paths;
        $this->data = $data;
    }
}
```

**Comment by jackmcdade** [comment] 2018-06-05 15:46
On the list! Closing this one because it's a Duplicate of #1441 but the info is helpful. Thanks!

**Closed by jackmcdade** 2018-06-05 15:46 UTC
Labels: feature request
