### ISSUE TITLE
Bug: Saving changes in CP - Fatal Error - Call to member XXX on null in XXX

### ISSUE THREAD

**Issue by fkwakkenbos** [statamic/v2-hub#1750] opened 2018-01-24 13:26 UTC
### Expected behaviour
We expect that everything keeps working without 404 or "Whoops something went wrong" messages.

### Actual behaviour
The front-end of the website keeps giving 404's on all pages
The control panel save action results in: "Whoops something went wrong" Exception message.

We've upgraded the VPS to 1GB of memory.
It doesn't look like the memory usage is exceeding the memory available.
Also changing the Memory limit within Statamic CP tot 128M doesn't matter.

We've disabled the "STATIC PAGE CACHING".

### Steps to reproduce
1.  We don't know how to reproduce this issue....
2.  It occurs when editing within the Control Panel

### Server Details

**Operating System**:
Ubuntu 16.04 LTS
**Web Server:**
1 CPU - 1GB memory SSD disk at Digital Ocean
**PHP Version:**
PHP 7.1
**Statamic Version:**
version: 2.8.3 (latest at this moment)
**Updated from an older Statamic or fresh install:**
fresh
**List of installed addons:**
https://github.com/statamic/spock

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```
[2018-01-24 08:49:57] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function data() on null in /home/forge/NEG.8TEST.NL/statamic/core/Http/Controllers/PagesController.php:33
Stack trace:
#0 [internal function]: Statamic\Http\Controllers\PagesController->pages()

[2018-01-24 08:49:49] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function uri() on null in /home/forge/NEG.8TEST.NL/statamic/bundles/Suggest/Modes/PagesMode.php:101
Stack trace:
#0 /home/forge/NEG.8TEST.NL/statamic/bundles/Suggest/Modes/PagesMode.php(55): Statamic\Addons\Suggest\Modes\PagesMode->getTree()

[2018-01-24 14:08:25] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function hasLocale() on null in /home/forge/NEG.8TEST.NL/statamic/core/Http/Controllers/PublishController.php:207
Stack trace:
#0 /home/forge/NEG.8TEST.NL/statamic/core/Http/Controllers/PublishEntryController.php(122): Statamic\Http\Controllers\PublishController->getLocales('944db7fc-bd3b-4...')
```
</details>

**Comment by fkwakkenbos** [comment] 2018-01-24 15:05
![image](https://user-images.githubusercontent.com/1029218/35339243-5f7f6e02-0120-11e8-979d-6226d5342a09.png)

**Comment by fkwakkenbos** [comment] 2018-01-25 13:43
Adding this to your .env solves the problem:
```
SESSION_DRIVER=cookie
```

**Comment by fkwakkenbos** [comment] 2018-01-26 07:29
https://laravel.io/forum/02-13-2015-difference-between-file-vs-cookie-session-driver

**Comment by fkwakkenbos** [comment] 2018-02-13 14:17
[Statamic BUG.pdf](https://github.com/statamic/v2-hub/files/1720181/Statamic.BUG.pdf)
We are running on the cookie sessions setting for a couple of weeks now, but unfortunately we've experienced the same issue again! :-( 
The commit which caused this issue is attached as a PDF export.
As you can see a very normal change...

**Comment by fkwakkenbos** [comment] 2018-02-13 14:19
[2018-02-13 15:02:09] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function data() on null in /home/forge/neg-itsolutions.nl/statamic/core/Http/Controllers/PagesController.php:33
Stack trace:
#0 [internal function]: Statamic\Http\Controllers\PagesController->pages()
#1 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#2 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('pages', Array)
#3 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\PagesController), Object(Illuminate\Routing\Route), 'pages')
#4 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\PagesController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'pages')
#10 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'pages')
#11 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#12 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /home/forge/neg-itsolutions.nl/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#18 /home/forge/neg-itsolutions.nl/statamic/core/Http/Middleware/Outpost.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#21 /home/forge/neg-itsolutions.nl/statamic/core/Http/Middleware/CP/Localize.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Statamic\Http\Middleware\CP\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#24 /home/forge/neg-itsolutions.nl/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#27 /home/forge/neg-itsolutions.nl/statamic/core/Http/Middleware/CpEnabled.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Statamic\Http\Middleware\CpEnabled->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#34 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#35 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#37 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/forge/neg-itsolutions.nl/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 /home/forge/neg-itsolutions.nl/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 /home/forge/neg-itsolutions.nl/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#66 /home/forge/neg-itsolutions.nl/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#67 {main}

**Comment by jasonvarga** [comment] 2018-02-13 14:38
This is the most elusive bug. We can't replicate it consistently. I feel like its a race condition.

The most recent error, did it happen when you were using the Control Panel or did you deploy a content change?

**Comment by fkwakkenbos** [comment] 2018-02-13 14:50
Using the Control panel. I agree with that the issue is not consistent.

**Comment by fkwakkenbos** [comment] 2018-02-13 14:56
We are using forge automatic deployment in combination with the Spock addon. The Spock addon triggers a deployment after something is published. The deployment also executes the command: "php please cache:clear". The deployment can happen at the same time a user is editing in the Control panel. Maybe this is related?

**Comment by fkwakkenbos** [comment] 2018-02-13 15:24
![image](https://user-images.githubusercontent.com/1029218/36157424-0afe74e4-10da-11e8-9761-139396d9b0c6.png)
![image](https://user-images.githubusercontent.com/1029218/36157495-370576a0-10da-11e8-8b3a-8efae58dcb79.png)
I would say this could be fixed to check the data (list of all pages) from the Stash Cache, before returning it...

**Comment by fkwakkenbos** [comment] 2018-03-02 09:09
I think it can be reproduced by saving a page within the control panel and at the same moment as running the cache:clear console command.

So this would be a timing issue when we enable the Quick Deploy function within Laravel Forge, this automaticly deploy's new changes pushed into the GIT repository.
When someone is editing content from the Control Panel, the Spock Add-on will automaticly commit and push new changes into the GIT repository. This will trigger a new deployment from Laravel Forge. Every deployment runs the php please cache:clear command.
When this happens at the same moment as someone is editing content from the Control Panel, the Stache gets broken.

We solved this issue by disabling the quick deploy feature of Laravel Forge, but this is more like a work-around.... Because now we have to manually deploy new changes...

**Comment by jackmcdade** [comment] 2018-03-02 20:21
What about altering the deploy script so it doesn't clear the cache? Unless you have static caching enabled, it'll still clear in the near future. You always have the option to clear it manually (like manually deploying) but don't _have_ to.

**Comment by fkwakkenbos** [comment] 2018-03-02 21:01
That would be a better solution, i agree!
But this is still a workaround...
Some changes won’t be available when we deploy new content.
This could be solved by clearing the cache manually, but how could we know when this would be necessary.
Probably we notice it too late, for example when te customer don’t see new changes...

How does the cache works?
Is it saved on disk?
For example changes in the searchable array for indexing collection entries, needs a cache clear to be applied for a fresh indexation.

**Comment by jackwakefield** [comment] 2018-03-07 12:59
I'm running into this in development and production randomly and when saving in the control panel, it seems to have increased in frequency since enabling a queue worker daemon.

**Comment by jackwakefield** [comment] 2018-03-07 14:21
This hastily thrown-together patch seems to fix the issues I've been running into:

```patch
diff --git a/statamic/core/Providers/StacheServiceProvider.php b/statamic/core/Providers/StacheServiceProvider.php
index 2a261f4..c6ed025 100644
--- a/statamic/core/Providers/StacheServiceProvider.php
+++ b/statamic/core/Providers/StacheServiceProvider.php
@@ -122,6 +118,12 @@ class StacheServiceProvider extends ServiceProvider
         // we should update on each request, or whether it's a glide route.
         $update = $this->shouldUpdateStache();
 
+        $this->stache->lock();
+
+        register_shutdown_function(function () {
+            $this->stache->unlock();
+        });
+
         try {
             // At this point the Stache is just an empty object. We'll want to load
             // (aka. 'hydrate') it. We'll also mark it as warmed. If it turns
@@ -142,6 +144,7 @@ class StacheServiceProvider extends ServiceProvider
             $this->updateStache();
         }
 
+        $this->stache->unlock();
         $this->stache->heat();
     }
 
@@ -229,9 +232,7 @@ class StacheServiceProvider extends ServiceProvider
             return;
         }
 
-        if (File::exists($lock = $this->stache->building_path)) {
-            File::delete($lock);
-        }
+        $this->stache->unlock();
 
         Config::set('system.ensure_unique_ids', false);
     }
diff --git a/statamic/core/Stache/Stache.php b/statamic/core/Stache/Stache.php
index 841dbbc..58c99df 100644
--- a/statamic/core/Stache/Stache.php
+++ b/statamic/core/Stache/Stache.php
@@ -69,6 +69,8 @@ class Stache
 
     public $taxonomies;
 
+    protected $locked;
+
     /**
      * Stache constructor.
      *
@@ -86,36 +88,50 @@ class Stache
         $this->temperature = self::TEMP_COLD;
     }
 
+    public function lock()
+    {
+        if (!$this->locked) {
+            $handle = fopen($this->building_path, 'c');
+            flock($handle, LOCK_EX);
+            fclose($handle);
+
+            $this->locked = true;
+        }
+    }
+
+    public function unlock()
+    {
+        if ($this->locked) {
+            $handle = fopen($this->building_path, 'c');
+            flock($handle, LOCK_UN);
+            fclose($handle);
+
+            $this->locked = false;
+        }
+    }
+
     /**
      * Change the temperature to cold
      *
      * @return void
      */
     public function cool()
     {
         $this->temperature = self::TEMP_COLD;
-
-        if (! File::exists($this->building_path)) {
-            File::put($this->building_path, true);
-        }
     }
 
     /**
      * Change the temperature to warm
      *
      * @return void
      */
     public function heat()
     {
         $this->temperature = self::TEMP_WARM;
-
-        if (File::exists($this->building_path)) {
-            File::delete($this->building_path);
-        }
     }
@@ -141,11 +157,16 @@ class Stache
      */
     public function isPerformingInitialWarmUp()
     {
-        return File::exists($this->building_path);
+        $handle = fopen($this->building_path, 'c');
+        $locked = !flock($handle, LOCK_EX | LOCK_NB);
+        fclose($handle);
+
+
+        return $locked;
     }
 
     /**
      * Set the locales used in the Stache
      *
      * @param array $locales
      */
```

**Comment by jasonvarga** [comment] 2018-03-07 14:24
Awesome stuff. Do you have a consistent way to reproduce the bug?

**Comment by fkwakkenbos** [comment] 2018-03-07 14:31
Nice ! Looks like a solution!

**Comment by jackwakefield** [comment] 2018-03-07 14:53
@jasonvarga Unfortunately not, I was only able to replicate it by load testing with 100-1000 requests per second

**Comment by jasonvarga** [comment] 2018-03-07 15:03
No worries. It looks promising. We'll give it another shot!

**Comment by jasonvarga** [comment] 2018-03-07 15:36
How many pages/entries do you guys have? (Ballpark - don't need the exact number)

**Comment by jackwakefield** [comment] 2018-03-07 15:56
In total ~1000-1500

**Comment by jasonvarga** [comment] 2018-03-07 16:44
@jackwakefield What kind of server are you testing this on?

**Comment by jackwakefield** [comment] 2018-03-07 16:49
Intel Xeon E3-1270v6 3.8Ghz + 16GB DDR4

I've just realised one possible factor, we use Redis for caching.

**Comment by jasonvarga** [comment] 2018-03-07 16:50
Oh sorry I mean like locally with Valet, or Digital Ocean with Apache, IIS, etc?

**Comment by jackwakefield** [comment] 2018-03-07 16:55
Dedicated server running CentOS 7, with nginx/1.13.9 and php-fpm 7.2.3

**Comment by jackwakefield** [comment] 2018-04-10 10:29
The patch above is working well (although it is missing an extra `building_path` check I've since changed, but not updated in the post).

I have ran into a few similar race conditions which I believe I've fixed with the following patch to Laravel:

```patch
diff --git a/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php b/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php
index 05f3edaf4..3a319b4f2 100755
--- a/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php
+++ b/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php
@@ -99,7 +99,7 @@ class FileStore implements Store

         $this->createCacheDirectory($path = $this->path($key));

-        $this->files->put($path, $value);
+        $this->files->put($path, $value, true);
     }

     /**
```

**Comment by TomS-** [comment] 2018-05-31 09:58
I can say, we are not using static page caching, however we have stache enabled. I've disabled stache now as edits will only happen in the CP.

The only thing I can add to this is we had two people logged into the same account when it happened. However, I'm keen to investigate this also

**Comment by jasonvarga** [comment] 2018-06-06 18:30
Closing this issue in favor of https://github.com/statamic/v2-hub/issues/2007

**Closed by jasonvarga** 2018-06-06 18:30 UTC
