### ISSUE TITLE
Must be of the type array, null given

### ISSUE THREAD

**Issue by pmeissner** [statamic/v2-hub#1174] opened 2017-01-03 21:51 UTC
### Actual behaviour
I get an email from my client every once in awhile saying that they get this error.

"There is an error saving the data. Please check your logs."

### Steps to reproduce
1.  Attaching an asset in a grid.
2.  Saving the entry.

### Server configuration
**Web server:**
Linux

**PHP version:**
7

**Statamic version:**
2.1.18

**Updated from an older Statamic or fresh install:**
Fresh

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
[2017-01-03 15:53:11] live.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Statamic\CP\FieldtypeFactory::create() must be of the type array, null given, called in /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/bundles/Grid/GridFieldtype.php on line 65 in /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/CP/FieldtypeFactory.php:21
Stack trace:
#0 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/bundles/Grid/GridFieldtype.php(65): Statamic\CP\FieldtypeFactory::create('text', NULL)
#1 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/bundles/Grid/GridFieldtype.php(55): Statamic\Addons\Grid\GridFieldtype->processField(Array, NULL)
#2 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/bundles/Grid/GridFieldtype.php(42): Statamic\Addons\Grid\GridFieldtype->processRow(Array)
#3 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/bundles/Grid/GridFieldtype.php(34): Statamic\Addons\Grid\GridFieldtype->performProcess(Array)
#4 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/CP/Publish/Publisher.php(200): Statamic\Addons\Grid\GridFieldtype->process(Array)
#5 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/CP/Publish/Publisher.php(86): Statamic\CP\Publish\Publisher->processFields()
#6 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/CP/Publish/EntryPublisher.php(25): Statamic\CP\Publish\Publisher->publish()
#7 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/Http/Controllers/PublishController.php(433): Statamic\CP\Publish\EntryPublisher->publish()
#8 [internal function]: Statamic\Http\Controllers\PublishController->save()
#9 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#10 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('save', Array)
#11 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), 'save')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'save')
#18 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'save')
#19 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#20 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#26 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/Http/Middleware/Outpost.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#29 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/Http/Middleware/Glide.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#64 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /home1/rnpanten/public_html/platinumlakemanagement.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /home1/rnpanten/public_html/platinumlakemanagement.com/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}  
```

What the markdown should look like:
```
docs_grid:
  - 
    docs_grid_img: f294d52d-4080-4ce5-a137-5303444750d7
    docs_grid_doc: 2a00dfd2-99b8-4ce6-b1a2-c206c9cf86a7
```

What the saved markdown ACTUALLY looks like:
```
docs_grid:
  - [ ]
```

**Comment by pmeissner** [comment] 2017-01-04 13:58
Hmmm… deleted the `- []` and cleared the cache and it started working again.

I noticed that Statamic is saving the data differently than it used to. Maybe an update along the way forced it to save like this…

```
docs_grid:
  - 
    docs_grid_img:
      - f294d52d-4080-4ce5-a137-5303444750d7
    docs_grid_doc:
      - 2a00dfd2-99b8-4ce6-b1a2-c206c9cf86a7
```

I have the max files set to 1 on each field.

**Comment by jackmcdade** [comment] 2017-03-16 16:30
Closing as it's actually a duplicate of #955, which is fixed for next release 👍

**Closed by jackmcdade** 2017-03-16 16:30 UTC
Labels: bug
