### ISSUE TITLE
CP Timeout prevents logging in again

### ISSUE THREAD

**Issue by sarahkyler** [statamic/v2-hub#1048] opened 2016-10-18 18:39 UTC
### Expected behaviour

Timing out should just require re-authenticating.
### Actual behaviour

On two different sites I've seen this happen where the logged in user is timed out at some point while active(in this case I was creating a page), and then can't log back in. Nothing showed up in logs, and invalid credentials is what's returned as the error each time. The session on the debugbar has the login_ value in it, and running the logout page removes that but doesn't allow you to login again. Only way I've found to login again is to reset to a plaintext password in the file and the let the system rehash it on login. Passwords are always the same, hashes are different. 
### Server configuration

**Operating system**:
CentOS
**Web server:**
Apache
**PHP version:**
5.6
**Statamic version:**
2.1.15
**Updated from an older Statamic or fresh install:**
Updated from older version
**List of installed addons:**
None

**Comment by sheldonkotyk** [comment] 2016-11-28 05:53
Clearing the cache seems to fix this problem and it allows logging in again.

**Comment by sheldonkotyk** [comment] 2016-11-28 05:53
I've had this happen on multiple sites now.

**Comment by rrelmy** [comment] 2016-12-15 10:27
I can confirm this issue on new installs of 2.1.18.
In my case I edited a page and saved it successfully but I was logged out and not able to login again.

What I observed is that the stache user cache file is empty
```
$ cat local/storage/framework/cache/stache/users/data 
9999999999a:0:{}
```

I can not find a way to reproduce it

**Comment by jasonvarga** [comment] 2017-08-18 15:05
Has this happened since upgrading beyond 2.6.2 ?

**Comment by sheldonkotyk** [comment] 2017-08-18 15:07
I haven't had it but I haven't been CPing enough to say that it is not going to. I'm fine with you closing it and I can resurrect it if it happens again.

**Comment by sheldonkotyk** [comment] 2017-08-18 15:08
https://github.com/statamic/v2-hub/issues/1560

Although this seems similar.

**Comment by sarahkyler** [comment] 2017-08-18 16:02
I'd be willing to bet it was a side effect of something happening in the cache. I've not experienced this issue in 2.6+ but I've also not been able to intentionally recreate the issue, it would just happen every now and again.

**Comment by jasonvarga** [comment] 2017-08-18 16:03
It's a weird one, for sure. I'm going to close this, but if it happens again just let us know.

**Closed by jasonvarga** 2017-08-18 16:03 UTC
Labels: needs more info

**Comment by matuvu** [comment] 2017-08-30 15:36
should reopen this as this is happening to our install the whole time. only thing that solves it is to clear the cache, but after 2 days it happens again.

**Comment by matuvu** [comment] 2017-08-30 15:37
Web server:
Apache
PHP version:
7.1
Statamic version:
2.6.6
Updated from older version
List of installed addons:
None
