### ISSUE TITLE
Grid field type is stacked when moved to different tab

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#2010] opened 2018-06-07 17:28 UTC
I setup a Grid field type in a global field set.

I moved the Grid field type to the "Navigation" tab (see image below) and now whenever I click on the Grid field type is stacked. If I resize the browser window then it immediately goes to a table layout.

![grid-field-type-stacked](https://user-images.githubusercontent.com/1793867/41115751-49200d20-6a3d-11e8-9ff8-bb176714bf1c.gif)

The site is on Statamic 2.9.6.

The mode for the Grid field type is properly set to table.

**Comment by jasonvarga** [comment] 2018-06-07 17:29
Dupe of #2003

**Closed by jasonvarga** 2018-06-07 17:29 UTC
