### ISSUE TITLE
Entries Listing not appearing in CP

### ISSUE THREAD

**Issue by j245** [statamic/v2-hub#664] opened 2016-05-03 16:09 UTC
### Steps to reproduce

Go to `cp/collections/entries/journal`
### Expected behaviour

A list of journal entries should appear
### Actual behaviour

Default chrome dialog message: 
`example.domain says: There was a problem retrieving data. Check your logs for more details.`
Only happens on staging URL (SSL), not locally.

Note: `cp/collections/entries/journal` (approx line 325)

```
<entry-listing inline-template v-cloak
        get="http://example.domain/cp/collections/entries/journal/get"
        delete="http://example.domai/cp/collections/entries/delete"
        reorder="http://example.domai/cp/collections/entries/reorder"
        sort="datestamp"
        sort-order="desc"
        :reorderable="false"
        :can-delete="true">
```
### Server configuration

**Operating system**:
Ubuntu 14.04.4 LTS
**Web server:**
Apache 2.4.7
**PHP version:**
5.5.9
**Statamic version:**
2.0.3
**Updated from an older Statamic or fresh install:**
Updated (but was occurring on 2.0.0) as well
**List of installed addons:**
Bespoke google re-captcha add-on
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
No error log generated (bizarrely)
```
#### Browser log

```
johnny-deps.js?v=2.0.3:8 Mixed Content: The page at 'https://example.domain/cp/collections/entries/journal' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.domain/cp/collections/entries/journal/get'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ johnny-deps.js?v=2.0.3:8

johnny-deps.js?v=2.0.3:8 XMLHttpRequest cannot load http://example.domain/cp/collections/entries/journal/get. Failed to start loading.(anonymous function) @ johnny-deps.js?v=2.0.3:8
```

**Comment by jackmcdade** [comment] 2016-05-03 17:24
Any chance there's a case-sensitive difference?

**Comment by j245** [comment] 2016-05-03 19:39
Don't think so no :( 

Where's that likely to be? 

The HTML that's outputted is all lowercase and it starts with `http://` and in the `site/settings/system.yaml` file the `locales` > `en` > `url` is set as the `https` domain, all lowercase.

**Comment by jackmcdade** [comment] 2016-05-03 19:59
What about the name of the folder of the collection?

**Comment by j245** [comment] 2016-05-03 20:04
Just checked and the collection folder names are all lowercase. It also works perfectly on my local setup (MAMP, OSX 10.11).

**Comment by jackmcdade** [comment] 2016-05-03 20:06
Are you running on SSL and logged into the CP also with https?

**Comment by j245** [comment] 2016-05-03 20:19
Yes, and interestingly the entries listing appears in the main dashboard under 'Recent Entries'

**Comment by jackmcdade** [comment] 2016-05-03 20:31
And in the collections section in the sidebar?

**Comment by j245** [comment] 2016-05-03 20:44
It's capitalized in the sidebar. Should that be lowercase too?

**Comment by jackmcdade** [comment] 2016-05-03 20:49
No thats fine. And when you click that link... broken?

**Comment by j245** [comment] 2016-05-04 08:56
Yes, when I click that link it throws the error. Likewise when I click the link in the main panel (i.e. not the sidebar) it's broken.

**Comment by jackmcdade** [comment] 2016-05-04 11:54
Can you send a zip of the collection folder?

**Comment by jackmcdade** [comment] 2016-05-04 13:45
Turned out to be Elastic Load balancer handling SSL for Apache but not manipulating the headers. We'll need to add a `forceSchema` setting for conditions like this.

**Comment by edalzell** [comment] 2016-05-05 00:01
wow, neat one.

**Comment by imsus** [comment] 2016-07-11 01:25
I've got the same issue. Any workaround for this? Should .htaccess file changed?

**Comment by imsus** [comment] 2016-07-11 09:13
**Copied from Slack**

I've found a workaround for this problem. It seems the cause was that my .htaccess way to force https is using `RewriteCond %{HTTP:X-Forwarded-Proto} !https `

I'm using this package https://github.com/fideloper/TrustedProxy and integrate it into statamic core middleware.

**Comment by j245** [comment] 2016-07-21 16:51
Just had this issue again as forgot to apply this fix when upgrading...

```
if (App::environment('ENVIRONMENT_NAME')) {
  URL::forceSchema('https');
}
```

Thought I'd drop it in here as a reminder :)

**Comment by kmccauley138** [comment] 2017-03-12 19:31
Hello @j245 I'm experiencing the same problem. Can you please tell me where to insert the above code.

**Comment by jackmcdade** [comment] 2017-03-16 21:13
We've got an explicit https setting coming in the next release so I'm gonna go ahead and close this one out so it doesn't get lost :)

**Closed by jackmcdade** 2017-03-16 21:13 UTC
