### ISSUE TITLE
Cant't remove form's column from control panle

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#950] opened 2016-09-12 17:12 UTC
### Steps to reproduce
1.  Go to forms and configure default contact form
2.  Remove one of columns
3.  Go back to forms and click contact you will see your removed column is still available there

### Server configuration
**Operating system**: Redhat

**Web server:** Apache

**PHP version:** 5.6

**Statamic version:** 2.1.9

**Updated from an older Statamic or fresh install:** Fresh

**Comment by jasonvarga** [comment] 2016-09-16 03:53
Dupe of #789

**Closed by jasonvarga** 2016-09-16 03:53 UTC
