### ISSUE TITLE
Glide cannot process asset named "img-*.jpg"

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1004] opened 2016-09-29 22:45 UTC
I had a number of assets named "img-gastown.jpg", "img-vancouver.jpg" and each was generating a broken image preview. When I visited the resized image url I got this error.

```
Whoops, looks like something went wrong.
1/1
FileNotFoundException in Server.php line 495:
Could not find the image `img/-gastown.jpg`.
in Server.php line 495
at Server->makeImage('img-gastown.jpg', array('w' => '200', 'h' => '200', 'fit' => 'crop', 's' => '6fc31792b955564b5d4712f5724b84e7')) in ImageGenerator.php line 133
at ImageGenerator->generate('img-gastown.jpg') in ImageGenerator.php line 113
at ImageGenerator->generateByAsset(object(Asset), array('w' => '200', 'h' => '200', 'fit' => 'crop', 's' => '6fc31792b955564b5d4712f5724b84e7')) in GlideController.php line 89
at GlideController->generateByAsset('7991443d-d60b-4aa1-8f65-a27cf876d5d4')
at call_user_func_array(array(object(GlideController), 'generateByAsset'), array('id' => '7991443d-d60b-4aa1-8f65-a27cf876d5d4')) in Controller.php line 256

```
![screenshot 2016-09-29 15 43 24](https://cloud.githubusercontent.com/assets/414211/18974935/831845dc-865b-11e6-8373-763405911a21.png)

**Comment by jasonvarga** [comment] 2016-09-30 14:35
Dupe of #729

**Closed by jasonvarga** 2016-09-30 14:35 UTC
