### ISSUE TITLE
Validation doesn't work with Replicator sets

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/v2-hub#1604] opened 2017-09-21 11:38 UTC
### Expected behaviour
Defining `validate` rules for a field in a Replicator set should work as intended.

### Actual behaviour
The field is not validated.

### Steps to reproduce
1. Create a normal text field with `validate: required|string`
2. Try to save the page leaving the field empty - an error occurs.
3. Create a replicator field with a simple set containing the definition as the normal text field.
4. Try to save the page leaving the the field in the replicator set empty - page is saved successfully.

### Server Details

**Operating System**: Alpine Linux 3.6.2

**Web Server:** nginx 1.12.1

**PHP Version:** 7.1.5

**Statamic Version:** 2.6.8

**Updated from an older Statamic or fresh install:** fresh

**Comment by jasonvarga** [comment] 2017-09-21 14:02
Dupe of #345

**Closed by jasonvarga** 2017-09-21 14:02 UTC
