### ISSUE TITLE
FR use preg_grep if array in matches, match, regex

### ISSUE THREAD

**Issue by nmquebb** [statamic/v2-hub#770] opened 2016-06-21 21:18 UTC
I was wondering if we can go from line 131 being `return preg_match($original_needle, $original_value);` to `return (is_array($original_value)) ? preg_grep($original_needle, $original_value) : preg_match($original_needle, $original_value);` incase we're trying to match against an array.

**Comment by jasonvarga** [comment] 2016-06-21 23:35
Dupe of #533 but appreciate the actual code suggestion. Thanks!

**Closed by jasonvarga** 2016-06-21 23:35 UTC
