### ISSUE TITLE
Error thrown when accessing Controller directly and not logged in

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#807] opened 2016-07-11 22:35 UTC
### Steps to reproduce
1. make a controller
2. log out of Statamic
3. use the browser auto-complete to go to the controller route

### Expected behaviour
Logged out user error

### Actual behaviour
ooky stack trace
```
ErrorException in PermissionComposer.php line 13:
Call to a member function permissions() on null (View: /Users/erin/Sites/stripe/site/addons/Admission/resources/views/admission.blade.php)
in PermissionComposer.php line 13
at CompilerEngine->handleViewException(object(FatalThrowableError), '1') in PhpEngine.php line 46
at PhpEngine->evaluatePath('/Users/erin/Sites/stripe/local/storage/framework/views/a3c054f8ab7cc9b6df9793f5f7a7fc4f', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'customers' => array(array('id' => 'sub_8mCMY6HlVmkX6T', 'roles' => array('d32e14fb-08c9-44c2-aaf8-21200852bafd'), 'first_name' => 'Erin', 'last_name' => 'Dalzell', 'email' => 'erin@thedalzells.org', 'password_hash' => '$2y$10$qA31P0BV57TSEG9x/BcOG.PRISYwlPebjNphJWcUnhs.2R6..hc1q', 'customer_id' => 'cus_8mCMq6fOjuk3cV', 'expiry_date' => '1499439510', 'plan' => 'Associate', 'amount' => '1000', 'auto_renew' => false)))) in CompilerEngine.php line 58
```

**Comment by lesaff** [comment] 2016-07-12 00:17
This is a duplicate of https://github.com/statamic/v2-hub/issues/150

**Closed** 2016-07-12 00:18 UTC
