### ISSUE TITLE
Rename asset on upload

### ISSUE THREAD

**Issue by stevieg83** [statamic/v2-hub#702] opened 2016-05-23 19:47 UTC
If I upload an asset with spaces in its name, Statamic should rename it replacing spaces with dashes or underscores

**Comment by lesaff** [comment] 2016-05-23 20:12
This is a duplicate of https://github.com/statamic/v2-hub/issues/74

**Comment by jasonvarga** [comment] 2016-05-23 20:17
Thanks Rudy, I knew this was opened somewhere.

**Closed** 2016-05-23 21:23 UTC
