### ISSUE TITLE
Assets to be slugified on upload

### ISSUE THREAD

**Issue by wesort** [statamic/v2-hub#604] opened 2016-04-16 15:57 UTC
Feature request for assets with non-url-friendly filenames to be renamed when uploaded by users.

ie: `Screen Shot 2016.04.16.png` becomes `screen-shot-2016-04-16.png`

### Workaround
Tell users to name files appropriately (a-z, 0-9, hyphens, underscores)

**Comment by lesaff** [comment] 2016-04-16 22:33
This is a duplicate of https://github.com/statamic/v2-hub/issues/74

**Comment by wesort** [comment] 2016-04-20 10:42
Oops. Doubly bad as I commented the other issue too.

**Closed** 2016-07-12 21:35 UTC
