### ISSUE TITLE
Pages bug: Clicking and dragging pages with children causes duplicates

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#1103] opened 2016-11-12 21:12 UTC
<img width="1094" alt="screen shot 2016-11-12 at 3 05 37 pm" src="https://cloud.githubusercontent.com/assets/510790/20240882/95a5e0fa-a8e9-11e6-997d-133c7c4fc66c.png">

So far I think this might be limited to cases when there is only one page with a child.

### Steps to reproduce
1.  In a clean install, create two top-level pages. Home and Page 1. Then create a third page (Page 2) that is a child of Page 1.
2.  Click and drag Page 1 anymore.
3.  A duplicate row will be created. Tested in Safari and Chrome.

### Server configuration
**Operating system**:

**Web server:**

**PHP version:**

**Statamic version:**
2.1.17

**Updated from an older Statamic or fresh install:**
Fresh

**List of installed addons:**
None

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```

**Comment by edalzell** [comment] 2016-11-12 21:43
Dupe of #1097

**Comment by than** [comment] 2016-11-12 21:46
@edalzell Slightly different action, but exact same result.

**Closed** 2016-11-12 21:46 UTC
