### ISSUE TITLE
Adding en as secondary locale causes 404 errors

### ISSUE THREAD

**Issue by peimn** [statamic/v2-hub#933] opened 2016-09-08 04:30 UTC
I added EN locale as second locale and want to use main URL for other locale as primary locale. But images get 404 errors...

### Server configuration
**Operating system**: Win

**Web server:** XAMPP

**PHP version:** 7.0.8

**Statamic version:** 2.1.7

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** ---

![screenshot_18](https://cloud.githubusercontent.com/assets/5695187/18337064/8a8ff2c0-75a2-11e6-8342-f8978c64909a.png)

**Comment by peimn** [comment] 2016-09-08 04:31
Also changing the order of locales causes 404 errors

**Comment by ebeauchamps** [comment] 2016-09-08 09:20
Because you have declared that the `en` local is associated with the following URL: mysite.local/en/

So all content is fetched from that URL, including images that are located in one place only and not in the /en/ path

Try with a clean install instead of using the default site

**Comment by peimn** [comment] 2016-09-08 13:14
I've defined en as secondary locale and for primary locale I've used another locale...

**Comment by jasonvarga** [comment] 2016-09-16 03:58
Dupe of #879

**Closed by jasonvarga** 2016-09-16 03:58 UTC
