### ISSUE TITLE
Cant Update to version 2.11.2 When Partials Used

### ISSUE THREAD

**Issue by bgarrant** [statamic/v2-hub#2265] opened 2018-11-27 19:16 UTC
When I upgrade a site to 2.11.2 on a 2.10.7 site using Bard and an Image field it will not load the edit page and hands on the image. https://cl.ly/71153238a2d9

The update completed fine
All pages just say "loading for the image" and Bard is not loading.  Here is the console: https://cl.ly/400e27384629

The issue has something to do with partials which Jason discovered already.  Please see see message ID 510493627089420308

**Comment by jasonvarga** [comment] 2018-11-29 14:49
Duplicate of #2242

**Closed by jasonvarga** 2018-11-29 14:49 UTC
