### ISSUE TITLE
Feature Request: Paginate CP for large numbers of entries

### ISSUE THREAD

**Issue by humanjpg** [statamic/v2-hub#1023] opened 2016-10-07 13:42 UTC
I have over 120 entries in a collection and finding that it's struggling to load. 

I reckon pagination over an amount (preferably with a setting to set the limit) might be a good look?

**Comment by jasonvarga** [comment] 2016-10-07 13:43
Dupe of #833

**Closed by jasonvarga** 2016-10-07 13:43 UTC
