### ISSUE TITLE
Adding form columns to the selected box doesn't work and vice versa

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#789] opened 2016-06-29 12:52 UTC
### Steps to reproduce
1. Create a new form field in the admin gui and click save on the form.
2. Click on the new field in the box at the top of the configure form page to add it to the selected fields box on the right.
3. Click save on the form configure page and the page refreshes and the field you just moved to the selected box is now back on the left like it was never moved.

![form_fields_not_working](https://cloud.githubusercontent.com/assets/1793867/16452485/c76bca42-3dd6-11e6-976c-20a409cb831f.gif)
### Expected behaviour

You should be able to add form fields to the selected box on the left.
### Actual behaviour

See steps to reproduce.
### Server configuration

**Operating system**:
OSX / Homestead

**Web server:**
Homestead / nginx and Apache

**PHP version:**
7.0.+

**Statamic version:**
2.0.7 and also 2.0.11

**Updated from an older Statamic or fresh install:**
Started with version 2 and all of the latest updates have been applied.

**List of installed addons:**
None.
#### Web server error log

There are no errors.
#### Statamic error log (`/local/storage/logs/statamic.log`)

There are no errors.
#### Browser log

There are no errors.

**Comment by jasonvarga** [comment] 2016-06-29 14:02
Dupe of #593 but I'll close that and leave this open. Yours is prettier and has a gif.

**Closed** 2016-11-18 20:21 UTC
Labels: pending release
