### ISSUE TITLE
Nav tag on multi language URLs will not display if starting from a subfolder ie: {{ nav from="{ segment_1 }"  }}

### ISSUE THREAD

**Issue by mc72** [statamic/v2-hub#682] opened 2016-05-12 22:21 UTC
### Steps to reproduce
1. Using nav tag {{ nav from="{ segment_1 }" max_depth="3"  }} on multi language site.
### Expected behaviour

Should see the menu based on the subfolder.
### Actual behaviour

No output.

Nav does not display if the locale is in the URL  (ie: http://domain.ltd/fr/frenchslug) and starting from a subfolder.  The segment variable doesn't appear to have an effect on a nav tag on a multi language site.

The proper multi language display will appear if you haven't converted the url to a multi language version (ie: http://domain.ltd/fr/english/folder/names)

{{ nav from="/" }} does display the correct nav/sub nav.

**PHP version:**
7.0

**Statamic version:**
2.04 (but same effect on all v 2.x sites)

**Updated from an older Statamic or fresh install:**
Updated from an older statamic

**Comment by andypillip** [comment] 2016-06-15 15:29
Can confirm this issue.

Additionally `is_current` and `is_parent` don't work properly.

Actually this should not only be related to locales, but to **any subfolder**. Because adding those locale-folders with single `index.php` files and adding `../` to the path is nothing different.

**Comment by edalzell** [comment] 2017-03-09 23:41
@mc72 is this still an issue?

**Comment by Rommert** [comment] 2017-03-21 09:55
@edalzell. This is still an issue. Can confirm....

**Comment by andypillip** [comment] 2017-04-10 18:44
To me it seems this is fixed…

I just did an update to 2.5.9.

**Comment by beeldr** [comment] 2017-07-25 10:03
To me this does not seems fixed, I use the next few lines for a subnav. 

It works fine in the main language (dutch) but when the page switches to english the segments change to english and it stops working. When manually setting the segments to the dutch segments (from="/leveranciers/famosa") it works fine in dutch and english.
 
`{{ nav from="/{segment_1}/{segment_2}"  }}
       <li class="subnav__item{{ if is_current || is_parent }} subnav__item--active{{ /if }}">
            <a href="{{ url }}">{{ title }}</a>
        </li>
 {{ /nav }}`

**Comment by andypillip** [comment] 2017-07-25 11:16
@beeldr I can confirm. It seems to be a regression issue?

I'm quite sure it was fixed in between. Can somebody test with 2.5?

**Comment by beeldr** [comment] 2017-07-27 06:44
@jasonvarga Could someone please look into this? I cant publish the site without this being fixed.

**Comment by andypillip** [comment] 2017-07-27 06:55
@beeldr did you try rolling back to 2.5?

**Comment by beeldr** [comment] 2017-07-27 06:57
@andypillip Jup 2.5.11 , no luck :(

**Comment by beeldr** [comment] 2017-07-27 13:59
@andypillip i don't have a 2.5.0 install file anywhere and can't find it at the statamic website.  I'd try it if I could get my hands on it.

**Comment by beeldr** [comment] 2017-07-28 06:25
@andypillip great thanks, for now i've replaced /{segment_1}/ with /leveranciers/ because only segment 2 is variable as the submenu is only active at those pages at this time so i can publish it.

**Comment by subpixelch** [comment] 2017-09-18 11:39
Please @jasonvarga reopen... it's again broken in 2.6.8 - please fix urgent 👍

**Closed** 2017-09-22 18:33 UTC
Labels: pending release
