### ISSUE TITLE
cp.settings_services is showing in settings menu and clicking it throws an error

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#1053] opened 2016-10-21 02:17 UTC
### Expected behaviour
There should be a proper name and clicking it shouldn't throw an error. (Or it shouldn't show at all.)

### Actual behaviour
See above.

### Steps to reproduce
1.  Upgraded from 2.1.15 from 2.0.11.
2.  Click on the Settings link.
3.  See the issue.

### Server configuration
**Operating system**:
Ubuntu.

**Web server:**
Apache / nginx

**PHP version:**
7

**Statamic version:**
2.1.15

**Updated from an older Statamic or fresh install:**
Updated from 2.0.11.

**List of installed addons:**
None.

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Whoops, looks like something went wrong.

1/1
FileNotFoundException in Fieldset.php line 55:
Fieldset(s) not found: [services]
in Fieldset.php line 55
at Fieldset::get('services', 'settings') in SettingsController.php line 32
at SettingsController->edit('services')
at call_user_func_array(array(object(SettingsController), 'edit'), array('name' => 'services')) in Controller.php line 256
at Controller->callAction('edit', array('name' => 'services')) in ControllerDispatcher.php line 164
at ControllerDispatcher->call(object(SettingsController), object(Route), 'edit') in ControllerDispatcher.php line 112
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 114
at ControllerDispatcher->callWithinStack(object(SettingsController), object(Route), object(Request), 'edit') in ControllerDispatcher.php line 67
at ControllerDispatcher->dispatch(object(Route), object(Request), 'Statamic\Http\Controllers\SettingsController', 'edit') in Route.php line 203
at Route->runWithCustomDispatcher(object(Request)) in Route.php line 134
at Route->run(object(Request)) in Router.php line 708
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Configurable.php line 23
at Configurable->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Configurable), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Authenticate.php line 62
at Authenticate->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Outpost.php line 51
at Outpost->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Outpost), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in DefaultLocale.php line 28
at DefaultLocale->handle(object(Request), object(Closure))
at call_user_func_array(array(object(DefaultLocale), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Router.php line 710
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 673
at Router->dispatchToRoute(object(Request)) in Router.php line 635
at Router->dispatch(object(Request)) in Kernel.php line 236
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in PersistStache.php line 22
at PersistStache->handle(object(Request), object(Closure))
at call_user_func_array(array(object(PersistStache), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in VerifyCsrfToken.php line 50
at VerifyCsrfToken->handle(object(Request), object(Closure))
at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in StartSession.php line 62
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Glide.php line 43
at Glide->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Glide), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Retrieve.php line 33
at Retrieve->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Retrieve), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Kernel.php line 122
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
at Kernel->handle(object(Request)) in index.php line 142
```

![screen shot 2016-10-20 at 10 13 17 pm](https://cloud.githubusercontent.com/assets/1793867/19584488/e7b1e83c-9712-11e6-983c-bfe378a6ecc7.png)

![screen shot 2016-10-20 at 10 13 26 pm](https://cloud.githubusercontent.com/assets/1793867/19584491/ed538ab6-9712-11e6-917c-ccab94ae4a47.png)

**Comment by jasonvarga** [comment] 2016-10-21 02:17
Dupe of #1049 and already fixed for next release.

**Closed by jasonvarga** 2016-10-21 02:17 UTC
