### ISSUE TITLE
Can't order assets by columns in CP

### ISSUE THREAD

**Issue by sebszocinski** [statamic/v2-hub#1589] opened 2017-09-07 00:36 UTC
I was surprised to find this missing? or is it a bug? but it seems like you can't sort or order assets by a column... and the default order is oldest assets first which seems odd to me, surely the newest assets would be listed first.

Anyway either being able to sort by column (and also across pages) would be very handy, or at the least an ability to set a default order like you can with collections. I tried adding `order: date` and that didn't work.

**Comment by wesort** [comment] 2018-04-19 00:09
Duplicate of #649

**Comment by timlockridge** [comment] 2018-04-27 15:12
Adding to this issue, which I don't think is a duplicate: On the Statamic web site, the [Asset Manager Screen Shot](https://docs.statamic.com/assets#control-panel) shows assets that are sortable by the Title column in the Asset Manager. In my installation, however, I can't sort by any of those columns, which I think is the bug that @sebszocinski was referring to.

**Closed** 2018-05-21 17:47 UTC
Labels: pending 2.9
