### ISSUE TITLE
FR: API to get all files in a folder

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-hub#926] opened 2016-09-05 17:23 UTC
If I store some data in Storage (in my addon), and I want to make a widget or controller to view the stored data, there's no way via the API to get that list.

Instead I have to use:
```
        /** @var \Statamic\Filesystem\FolderAccessor $storage */
        $storage = Folder::disk('storage');

        $storage->getFiles()
```

Would be nice to have `Folder::getFiles()`

**Comment by jasonvarga** [comment] 2016-09-05 17:38
Dupe of #629 

There is a way to do what you're asking, there's just no helper method for it.

```
use Statamic\API\File;
use Statamic\API\Folder;
use Statamic\API\YAML;

private function getStorageFiles()
{
    $files = Folder::disk('storage')
        ->getFilesByTypeRecursively('addons/' . $this->getAddonClassName(), 'yaml');

    return collect($files)->map(function ($path) {
        return YAML::parse(File::disk('storage')->get($path));
    });
}
```

**Closed by jasonvarga** 2016-09-05 17:38 UTC
